dist: focal
sudo: required
language: bash
services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
  - docker build -t packer-ansible -f play-travis/Dockerfile-packer-ansible play-travis
  - curl https://raw.githubusercontent.com/loktionovam/otus-homeworks/2018-05/run.sh | bash
install:
  - sudo pip install -r ansible/requirements.txt
  - ansible --version
  - ansible-lint --version
  - docker --version

before_script:
  - play-travis/terraform-init.sh
  - ssh-keygen -f ~/.ssh/appuser -q -N ""

script:
  - play-travis/packer-validate.sh
  - play-travis/tflint.sh
  - play-travis/terraform-validate.sh
  - ansible-lint -v ansible/playbooks/*.yml
# notifications:
#   slack:
#     rooms:
#       secure: XOdt25D36GlTHDOyw1FZcNfbTkqhn85s2mbnDiHCZWCP+6LEYhSH3a0MlEQ96rBr7xMvgKiSmz/aEPtLpCL3j5xB6tZHzc+ZwwtuzmLH2CDKNVSxVO5EtKQ6EwHET1ebrL38x03wxabl7+e8EMGDI5CWN3RxiP3YxzDnXkLNMb7JZLgn5aqMVMGC4cTuW0Tyu5eYVg5Y1Ckxlt0RKTt0C56IzoU3QZSmxoBrkhvq0+DKnxWrCci4U/RSAw90JICdkLAPGyoLl2PEkYk+0G/GzVP1gK1r8llZjR5Lj+txvPQ2EUfA9L0f3hUJhOixpL44Kpyu5HVHklPLDp2V+YZw6LwxWap4EPPFreGRuTDJ8xTKZNt0eYYiXIW0pAYnNtVU74p73b2FRPZF8kjHxpgWLJ2AJtadjF1FD/58f7y0LyHkuQEe8zBiTwDh5N6eHCb/Xit52L/oGJoDNDYLl9wA9RXfb+OuL3s+faltr+hswfZr5Hnmd8U9GKtAtOmEQznQewi+55nyOU+VBY2fkPtBEbwHlbONzcljEIQM/kKjIMJAeSHQVCg/IUwuxxJDsRRCTICqOvZyGOzTkIY9Ph+/8RlgoXDzgFsBELh22joFeqGzeCvb2OH0r+PXi9Bes0UvSng7G875NMmfjGi9uJyLMW7RDcTUHLL26nAF0eJy6Ks=
