---
- name: Install ruby
  hosts: all

  vars:
    ruby_packages:
      - ruby-full
      - ruby-bundler
      - build-essential

  tasks:
    - name: Install ruby and related packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - "{{ ruby_packages }}"
      become: yes
