---
- name: Setup google cloud platform dynamic inventory via ansible gce.py
  hosts: localhost
  connection: local

  vars:
    ansible_branch: stable-{{ ansible_version.major}}.{{ ansible_version.minor }}
    
  vars_prompt:
    
    - name: "gce_service_account_pem_file_path"
      prompt: Enter path to GCE service account pem file
      default: credentials/gce-service-account.json
      private: no

  tasks:

    - name: Load variables from GCE service account pem file
      include_vars:
        file: "{{ gce_service_account_pem_file_path }}"
        name: gce_service_account

    - name: Install GCE ansible module requirements
      pip:
        name: apache-libcloud

    - name: Clone ansible repository
      git:
        repo: 'https://github.com/ansible/ansible'
        dest: /tmp/ansible
        depth: 1
        version: "{{ ansible_branch }}"

    - name: Create ansible gce dynamic inventory directory
      file:
        path: inventory_gce
        state: directory

    - name: Copy ansible gce.py from cloned repo to inventory directory
      copy:
        src: /tmp/ansible/contrib/inventory/gce.py
        dest: inventory_gce
        mode: 0755

    - name: Copy gce.ini configuration
      template:
        src: templates/gce.ini.j2
        dest: inventory_gce/gce.ini

    - name: Switch to ansible gce dynamic inventory in ansible.cfg
      ini_file:
        path: ansible.cfg
        section: defaults
        option: inventory
        value: ./inventory_gce
